---

- name: Dependencies
  apt:
    state: present
    name:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https

- name: Caddy Apt Key
  ansible.builtin.apt_key:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key

- name: Caddy Apt Repo
  ansible.builtin.apt_repository:
    repo: deb https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main

- name: Caddy
  apt:
    update_cache: yes
    state: present
    name: caddy

- name: Allow HTTP
  community.general.ufw:
    rule: allow
    port: http

- name: Allow HTTPS
  community.general.ufw:
    rule: allow
    port: https
